global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['{{ node_exporter_proxy_ip }}:9100']

  - job_name: 'mac-node'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.1.33:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['{{ cadvisor_proxy_ip }}:8080']