---
- hosts: orangepi

  tasks:
    - name: Create directory for Loki server
      file:
          path: "{{ n8n_dir }}"
          state: directory
          mode: 0755

    - name: Create a docker-compose.yml file
      ansible.builtin.template:
        src: n8n/docker-compose.yml
        dest: "{{ n8n_dir }}"

    - name: Create a .env file
      ansible.builtin.template:
        src: n8n/.env
        dest: "{{ n8n_dir }}"

    - name: Run `docker-compose up`
      command: "sudo docker compose -f {{ n8n_dir }}/docker-compose.yml up -d --force-recreate"
