---
- hosts: orangepi

  tasks:
    - name: Create directory for Loki server
      file:
          path: "{{ monitoring_dir }}/etc/loki"
          state: directory
          mode: 0755

    - name: Create directory for Prometheus server
      file:
          path: "{{ monitoring_dir }}/prometheus/data"
          state: directory
          mode: 0755

    - name: Create directory for Promtail server
      file:
          path: "{{ monitoring_dir }}/etc/promtail"
          state: directory
          mode: 0755

    - name: Create directory for Grafana server
      file:
          path: "{{ monitoring_dir }}/grafana"
          state: directory
          mode: 0755

    - name: Create a loki-config.yml file
      ansible.builtin.template:
        src: monitoring/loki-config.yml
        dest: "{{ monitoring_dir }}/etc/loki"

    - name: Create a prometheus.yml file
      ansible.builtin.template:
        src: monitoring/prometheus.yml
        dest: "{{ monitoring_dir }}/prometheus"

    - name: Create a promtail-config.yml file
      ansible.builtin.template:
        src: monitoring/promtail-config.yml
        dest: "{{ monitoring_dir }}/etc/promtail"

    - name: Create a docker-compose.yml file
      ansible.builtin.template:
        src: monitoring/docker-compose.yml
        dest: "{{ monitoring_dir }}"

    - name: Create a Dockerfile file
      ansible.builtin.template:
        src: monitoring/Dockerfile
        dest: "{{ monitoring_dir }}"

    - name: Create a .env file
      ansible.builtin.template:
        src: monitoring/.env
        dest: "{{ monitoring_dir }}"

    - name: Run `docker-compose build`
      command: "sudo docker compose -f {{ monitoring_dir }}/docker-compose.yml build --no-cache"
      register: docker_compose_output

    - name: Run `docker-compose up`
      command: "sudo docker compose -f {{ monitoring_dir }}/docker-compose.yml up -d --force-recreate"
      register: docker_compose_output

    - name: Debug output
      debug:
        var: docker_compose_output.stdout_lines