---
- hosts: orangepi

  tasks:
    - name: Create directory for Home Assistant
      file:
          path: "{{ homeassistant_dir }}/config"
          state: directory
          mode: 0755

    - name: Create a docker-compose.yml file
      ansible.builtin.template:
        src: homeassistant/docker-compose.yml
        dest: "{{ homeassistant_dir }}"

    - name: Create a .env file
      ansible.builtin.template:
        src: homeassistant/.env
        dest: "{{ homeassistant_dir }}"

    - name: Create a configuration.yaml file
      ansible.builtin.template:
        src: homeassistant/configuration.yaml
        dest: "{{ homeassistant_dir }}/config"

    - name: Run `docker-compose up`
      command: "sudo docker compose -f {{ homeassistant_dir }}/docker-compose.yml up -d --force-recreate"
      register: docker_compose_output

    - name: Install HACK
      community.docker.docker_container_exec:
        container: homeassistant
        command: /bin/bash -c "wget -O - https://get.hacs.xyz | bash -"
      register: result

    - name: Print the result
      debug:
        var: result

    - name: Restart container command
      command: "docker restart homeassistant"
