---
- hosts: orangepi
  become: true

  tasks:

    - name: Create directory for DNS server
      file:
          path: "{{ dns_dir }}"
          state: directory
          mode: 0755

    - name: Create a .env file
      ansible.builtin.template:
        src: dns/.env
        dest: "{{ dns_dir }}"

    - name: Create a docker-compose.yml file
      ansible.builtin.template:
        src: dns/docker-compose.yml
        dest: "{{ dns_dir }}"

    - name: Run `docker-compose up`
      command: "sudo docker compose -f {{ dns_dir }}/docker-compose.yml up -d --force-recreate"

    - name: Create a orangepi-default.yaml netplan file
      ansible.builtin.template:
        src: dns/orangepi-default.yaml
        dest: /etc/netplan

    - name: Apply netplan
      command: netplan apply
      async: 45
      poll: 0