version: '3.8'
services:
  ansible:
    build: .
    volumes:
      - ./hosts:/etc/ansible/hosts
      - ./host_vars:/etc/ansible/host_vars
      - ./ansible.cfg:/etc/ansible/ansible.cfg
      - ./playbooks:/playbooks
      - ~/.ssh:/root/.ssh/
    networks:
      - ansible

networks:
  ansible:
